In [1]:
import math

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
print(np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [9]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [10]:
arr = np.array([1,2,3,4,5,6,7,8])

In [11]:
np.append(arr,[1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [12]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [13]:
arr = np.array([2,1,5,3,4,6,8])

In [14]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 8])

In [15]:
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7]],
                         
                          [[0,1,2,3],
                           [4,5,6,7]],
                           
                          [[0,1,2,3],
                           [4,5,6,7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [16]:
array_example.ndim

3

In [18]:
array_example.shape

(3, 2, 4)

In [19]:
array_example.size

24

In [20]:
arr_one = np.array([[1,2,3,4,5]])

In [21]:
arr_one.ndim

2

In [22]:
arr_one.size

5

In [23]:
arr_one.shape

(1, 5)

In [24]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [25]:
b = a.reshape(3,2)

In [26]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [27]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [30]:
np.reshape(a,(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
a = np.array([1,2,3,4,5,6])

In [32]:
a.shape

(6,)

In [34]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [35]:
row_vector = a[np.newaxis,:]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [36]:
col_vector = a[:,np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [37]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [38]:
b = np.expand_dims(a,axis=1)
print(b.shape)
print(b)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [39]:
c = np.expand_dims(a,axis=0)
print(c.shape)
print(c)

(1, 6)
[[1 2 3 4 5 6]]


In [40]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [41]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
print(a[a>=5])
print(a[a%2==0])

[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


In [43]:
five_up = a>=5
print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [45]:
divisible_two = a[a%2==0]
print(divisible_two)

[ 2  4  6  8 10 12]


In [47]:
c = a[(a>2)&(a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [48]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1=arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [49]:
a_1 = ([[1,1],[2,2]])
a_2 = ([[3,3],[4,4]])
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [50]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [52]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],[13,14,15,16,17,18,19,20,21,22,23,24]])

In [53]:
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [54]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [55]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
a = np.array([1,2,3,4])
a.sum()

10

In [59]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [60]:
b.sum(axis=0)

array([3, 3])

In [62]:
b.sum(axis=1)

array([2, 4])

In [63]:
data = np.array([1,2])
data

array([1, 2])

In [64]:
ones = np.ones(2)
ones

array([1., 1.])

In [65]:
data + ones

array([2., 3.])

In [66]:
data*data

array([1, 4])

In [67]:
data/data

array([1., 1.])

In [68]:
data*2

array([2, 4])

In [69]:
A = np.array([[0.45053314,0.1729677,0.34376245,0.5510652],[0.54627315,0.05093587,0.41167661,0.55645993],[0.12697628,0.82485143,0.26590556,0.56914101]])

In [70]:
print(A)

[[0.45053314 0.1729677  0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.41167661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56914101]]


In [71]:
A.sum()

4.87054833

In [73]:
A.min()

0.05093587

In [74]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [75]:
A.max()

0.82485143

In [76]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [77]:
A.std()

0.21392253429086902

In [82]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.53448428 0.70631049]
 [0.87483455 0.47641732]
 [0.59974296 0.19902533]]


In [84]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [85]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [86]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [87]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [88]:
print(data+ones_row)

[[2. 3.]
 [4. 5.]]


In [89]:
a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8],[9,10],[11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [90]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])